### ISSUE TITLE
Out of memory CUDA

### ISSUE THREAD

**Issue by calibretaliation** [huggingface/instruction-tuned-sd#12]
Hello, thank you for the great work and tutorial. Im currently follow your instruction here: [https://huggingface.co/blog/instruction-tuning-sd](url) but I got outofmemory error.
My specs are 2x 12Gb RTX 3060. I was able to train a LORA text2image tutorial, but fail this one. Can you please help me with this case? what should I do to be able to train instruc pix2pix with my custom dataset ?
![image](https://github.com/huggingface/instruction-tuned-sd/assets/72718669/368c1122-c566-4c6d-8fd2-5f7168cd6068)

**Comment by sayakpaul** [comment]
It's full fine-tuning, so 3060 might not be enough.
