### ISSUE TITLE
Fine tuning on own dataset

### ISSUE THREAD

**Issue by unmo** [huggingface/instruction-tuned-sd#13]
Is there a way to do finetuning on my own dataset?
In particular, I don't know how to give a own dataset and directory structure.

**Comment by sayakpaul** [comment]
You can refer to the post here to know more: https://huggingface.co/blog/instruction-tuning-sd

**Comment by unmo** [comment]
Thank you. 
Should it be a huggingface dataset datatype as per the example provided? Or is it possible to train with a low-level data type such as a python dictionary?

**Comment by unmo** [comment]
I'm sorry I can not understand.
The post presented gave an example of giving a dataset to be cartooned using a subset of Image net.
But what I would like to do is to use my own dataset to give a dataset with various other processing various processing.

**Comment by sayakpaul** [comment]
You can configure the dataset as per your choice as long as you maintain the format presented in the post. You might have to configure your dataloader and dataset class in case you don't want to make use of `datasets` library.

**Comment by unmo** [comment]
Thank you your response, I'll try it.
