### ISSUE TITLE
There was a problem uploading own dataset

### ISSUE THREAD

**Issue by AnnyOrange** [huggingface/instruction-tuned-sd#14]
When I run `python export_to_hub.py`
there was an error _requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/datasets/Text-style-dataset/preupload/main_
_Repository Not Found for url: https://huggingface.co/api/datasets/Text-style-dataset/preupload/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Note: Creating a commit assumes that the repo already exists on the Huggingface Hub. Please use `create_repo` if it's not the case._
I have no idea why this happens?

**Comment by sayakpaul** [comment]
You need to create an empty dataset first on the Hub and then use the script. Will make a note in the README.

**Comment by AnnyOrange** [comment]
Sorry but it still give the same&nbsp;error message.







I try my best to fix this.&nbsp;I checked if the Repository exists, and I'm sure the repository exists, I'm sure the Repository is public, and I also logged in huggingface(huggingface-cli login) before python export_to_hub.py. But...

                       
原始邮件
                       
                     

发件人："Sayak Paul"< ***@***.*** &gt;;

发件时间：2024/1/17 16:11

收件人："huggingface/instruction-tuned-sd"< ***@***.*** &gt;;

抄送人："AnnyOrange"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [huggingface/instruction-tuned-sd] There was a problem uploadingown dataset (Issue #14)




 
You need to create an empty dataset first on the Hub and then use the script. Will make a note in the README.

**Comment by sayakpaul** [comment]
Then I don't know what's happening. Might be worth trying to reproduce the issue in a minimal manner.

**Comment by AnnyOrange** [comment]
If I cannot create my dataset and upload it in hugging face, can I just preserve it locally and change the finetune_instruct_pix2pix.py?

**Comment by sayakpaul** [comment]
You can and that needs changes in the `finetune_instruct_pix2pix.py` script.

**Comment by AnnyOrange** [comment]
I figured out what the problem was, but still haven't solved it. I just can’t access https://huggingface.co/api/datasets/text-style/preupload/main
I replaced text-style with the name of the existing data set and still can't access it. So it should be a network problem, or the huggingface function?

**Comment by AnnyOrange** [comment]
The problem is solved. The solution is to replace DS_NAME="<dataset_id>" with "<organization>/<dataset_id>".
Really appreciate your continued help!

**Comment by sayakpaul** [comment]
Glad you figured it out. I am going to close the issue then :)
