### ISSUE TITLE
Pix-to-Pix as Viton?

### ISSUE THREAD

**Issue by Bilal143260** [huggingface/instruction-tuned-sd#15]
Is it a good idea to train pix-to-pix-instruct to act like a viton (virtual try-on)? The training data would include images of cloth and prompts as input and a model wearing that dress as ground truth.

**Comment by sayakpaul** [comment]
It might be better to use IP Adapters for that.

**Comment by sonadorr** [comment]
> It might be better to use IP Adapters for that.

I also believe that is the way to go.

**Comment by Bilal143260** [comment]
Thanks @sayakpaul and @sonadorr for your suggestions. If you guys are open to collaborations or consultancy,  me and my team are working on developing a viton.
