### ISSUE TITLE
Training ipynb or colab file.

### ISSUE THREAD

**Issue by roshan2024nar** [huggingface/instruction-tuned-sd#16]
Hello,
Thank you for this awesome work

i had some custom style images and wanted to try training but unable to understand some factors such as how to push on hub etc.
is there any colab or ipynb or any video of training available then please share.

**Comment by sayakpaul** [comment]
```python
pipeline.push_to_hub("checkpoint-id")
```

should work. 

```python
pipeline.saved_pretrained("checkpoint-id", push_to_hub=True)
```

would work as well. 

Just make sure you're on the latest `diffusers` version and are authenticated to push to the Hub using `huggingface-cli login`.
