### ISSUE TITLE
Fine-Tuning Text Encoder of IP2P

### ISSUE THREAD

**Issue by mvp18** [huggingface/instruction-tuned-sd#17]
Hi,

Not really a question related to the current repository, but could you provide some insights on how to fine tune the text encoder of Instruct-Pix2Pix for a custom token using textual inversion on a small set of images?

In the hugging face example code for textual inversion, a set of sample prompts are defined as here - https://github.com/huggingface/diffusers/blob/main/examples/textual_inversion/textual_inversion.py#L441-L491 where the sample prompts are designed for a text2image pipeline. I would assume that the prompts for an IP2P model would mostly be instructions on how to change a given image, so not really sure what all generic templates to use.

Also, even if we are given such a set of templates, would a similar noise prediction loop be sufficient for finetuning the text encoder for the new token(s) or would I need a small custom dataset?

Would appreciate any kind of help in this regard. Thanks

**Comment by sayakpaul** [comment]
Text encoder of IP2P doesn't differ in terms of the architecture used in SD. So, similar principles for SD textual inversion should apply here. 

> Also, even if we are given such a set of templates, would a similar noise prediction loop be sufficient for finetuning the text encoder for the new token(s) or would I need a small custom dataset?

What does this? For fine-tuning, you need a dataset anyway.

**Comment by mvp18** [comment]
Sorry, should have been a bit clearer. I meant, would I need a dataset in the style of one that is used to train instruct pix2pix like in this repository or like in the diffusers here - https://github.com/huggingface/diffusers/tree/main/examples/instruct_pix2pix where we have an original image, an edit instruction and the edited image as a data sample? Or is a simple dataset of a few images for fine-tuning the text encoder enough?

I guess that a dataset with the original image, edit instructions, and the edited image would only be required if I want to train the UNet, but I am not entirely sure.

**Comment by sayakpaul** [comment]
For fine-tuning the text encoder with the UNet of the InstructPix2Pix the data schema needs to follow what's discussed in https://github.com/huggingface/diffusers/tree/main/examples/instruct_pix2pix. 

> I guess that a dataset with the original image, edit instructions, and the edited image would only be required if I want to train the UNet, but I am not entirely sure.

Only if the UNet is the original SD UNet and not from InstructPix2Pix.

**Comment by mvp18** [comment]
Hi,

Thanks for the clarification. One final question on this - what would be a good sample size for fine-tuning the text encoder of IP2P? Would a handful of images be sufficient for learning a concept like in the original textual inversion example, as the UNet is not fine-tuned, just the text encoder? Or would I need a dataset at least of the scale of the ones used in your examples?

Thanks

**Comment by sayakpaul** [comment]
Experimentation is the key here.
