### ISSUE TITLE
How to use a custom image for validation 

### ISSUE THREAD

**Issue by roshan2024nar** [huggingface/instruction-tuned-sd#22]
Hello,
I tried using a custom image for validation since I'm training it on  a custom style i uploaded my val image on hub as the mountain.png but it always gives me error for unidentified also for mountain.png it shows validation summary on wandb but for my val image it shows nothing.
Do i need to change something somewhere also how does it compare the val images for loss do  i need to put the style image of original image somewhere

**Comment by sayakpaul** [comment]
You are asking for debugging help. I would suggesting debugging things on your own here.

**Comment by roshan2024nar** [comment]
I'm asking have you ever used a custom val image ? or a different prompt  while training

**Comment by sayakpaul** [comment]
I have. You need to provide a direct downloadable link to the validation image and it should work.
