### ISSUE TITLE
[ERROR] Error when fine-tuned model in Colab.

### ISSUE THREAD

**Issue by lynguyenminh** [huggingface/instruction-tuned-sd#5]
Hi, thanks for the great work!

I ran the fine-tuned script, and it raised an error as below, how to fix it?

![image](https://github.com/huggingface/instruction-tuned-sd/assets/82688630/9d2f305b-aae7-40ed-be73-8abfa99ad068)

Thanks

**Comment by sayakpaul** [comment]
It's not an error, it's a warning.

**Comment by sayakpaul** [comment]
I would consider running it from a dedicated terminal.

**Comment by lynguyenminh** [comment]
> I would consider running it from a dedicated terminal.

Do you mean that it can only be run in the terminal of local Ubuntu? I don't have a GPU, so I use Colab for free. Is there any solution for using Colab? Thanks.

**Comment by sayakpaul** [comment]
We should be able to see the full output on Colab. Currently, it does not show that I think. But that is not related to our code, so, immediately we don't have an answer.

**Comment by eren23** [comment]
This is because colab doesn't correctly display the remainder of the error, but in my case, it was about a method being used the old way and caused it to break the run.
    ```
accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
        project_dir=logging_dir,
        project_config=accelerator_project_config,
    )
```
It turns out the logging_dir is not passable to accelerator here and instead it's expecting something called a project_dir

**Comment by sayakpaul** [comment]
Would you be maybe open to contribute a PR?

**Comment by eren23** [comment]
> Would you be maybe open to contribute a PR?

Sure, I can open one tomorrow, no problem

**Comment by eren23** [comment]
> Would you be maybe open to contribute a PR?

Hey just sent that in along with other minor changes, sorry for taking forever I just forgot.

**Comment by roshan2024nar** [comment]
Hey,
When i run on colab with same code and cmd i get  out of memory error it works fine till start of the step and suddenly 

![image](https://github.com/huggingface/instruction-tuned-sd/assets/77958364/75785fff-1d4a-487e-8104-d8fd15d104ce)
