### ISSUE TITLE
Fine-tuning with local models and dataset

### ISSUE THREAD

**Issue by qingyangdong** [huggingface/instruction-tuned-sd#8]
Hi!

I'm wondering if there is a way to finetune with local models and datasets (or from my drive if on colab)? I've been setting "--dataset_dir" to my datasets both locally and on colab but neither worked. When I tried to fine-tune with the given IDs it would throw an error and ask for a token from huggingface. Is there a way to work around it? 

Thank you!

**Comment by sayakpaul** [comment]
You can provide a local path containing the model checkpoints as long as they are compatible. 

For datasets, as long as you can ensure a compatible structure, it should be fine. Otherwise, you will need to rework that dataloader.

**Comment by qingyangdong** [comment]
Thank you for such a quick response! I encountered another issue when saving the model: when I pass in

```
  --output_dir=$OUTPUT_DIR \
  --report_to=wandb \
  --push_to_hub \
  --hub_token=<my_token> \
  --hub_model_id=$OUTPUT_DIR
```
my own model saved at OUTPUT_DIR on the hub was not updated. Alternatively, I passed in only
```
 --output_dir=$OUTPUT_DIR
```
but the model was not saved to my local directory either. Would you happen to know what the issue might be?

Thank you again!

**Comment by sayakpaul** [comment]
You should pass `--push_to_hub`.

**Comment by qingyangdong** [comment]
yeah, I passed that in my first kind of set up but it didn't update my hub directories. Did you pass only `--push_to_hub`?

```
 --push_to_hub \
  --hub_token=<my_token> \
  --hub_model_id=$OUTPUT_DIR
```

Thank you!

**Comment by qingyangdong** [comment]
Solved the issue. Will update readme.
